import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv
import os
import sys

load_dotenv()

# Название нового плейлиста
NEW_PLAYLIST_NAME = "Spotify Tracker Music"

# !!! ВАЖНО: show_dialog=True заставляет Spotify снова спросить разрешения !!!
sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
    client_id=os.getenv("SPOTIPY_CLIENT_ID"),
    client_secret=os.getenv("SPOTIPY_CLIENT_SECRET"),
    redirect_uri=os.getenv("SPOTIPY_REDIRECT_URI"),
    scope="user-follow-read playlist-modify-public playlist-modify-private",
    open_browser=False,
    show_dialog=True,  # <--- ЭТА СТРОКА РЕШАЕТ ПРОБЛЕМУ
    cache_handler=spotipy.cache_handler.CacheFileHandler(cache_path=".cache")
))

print("\n--- НАЧАЛО СОЗДАНИЯ ПЛЕЙЛИСТА ---")

try:
    # 1. Получаем ID пользователя
    user = sp.current_user()
    user_id = user['id']
    print(f"Авторизован как: {user['display_name']} (ID: {user_id})")

    # 2. Создаем плейлист
    # Пробуем создать ОТКРЫТЫЙ плейлист (иногда на приватные бывает глюк прав)
    print("Пытаюсь создать плейлист...")
    
    playlist = sp.user_playlist_create(
        user=user_id, 
        name=NEW_PLAYLIST_NAME, 
        public=True,  # Делаем публичным, чтобы избежать лишних ошибок прав
        description="Auto-generated by Spotify Tracker"
    )
    
    print("\n" + "="*40)
    print(f"✅ УСПЕШНО! Плейлист создан!")
    print("="*40)
    print(f"НОВЫЙ PLAYLIST_ID: {playlist['id']}")
    print("="*40)
    print("СКОПИРУЙ ЭТОТ ID В ФАЙЛ .env !!!")
    print("="*40 + "\n")

except spotipy.exceptions.SpotifyException as e:
    print("\n❌ ОШИБКА SPOTIFY API:")
    print(f"Код: {e.http_status}")
    print(f"Сообщение: {e.msg}")
    print("\nСОВЕТ: Если ошибка 403 - вы точно нажали 'AGREE' (Принять) на зеленой кнопке?")
    
except Exception as e:
    print(f"\n❌ ОБЩАЯ ОШИБКА: {e}")